# Generated by Django 5.2.17 on 2026-09-07 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('slot', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('done', 'Done')], default='available', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chores.partner')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chores.schedule')),
            ],
            options={
                'ordering': ['due_date', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('slot__in', [1, 2])), name='two_partner_slots'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.UniqueConstraint(fields=('schedule', 'due_date'), name='unique_schedule_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('owner__isnull', True), ('status', 'available')), models.Q(('completed_at__isnull', True), ('owner__isnull', False), ('status', 'claimed')), models.Q(('completed_at__isnull', False), ('owner__isnull', False), ('status', 'done')), _connector='OR'), name='valid_chore_state'),
        ),
    ]
